<div class="main">
	
	<div class="datos">
		<div class="estados">	
			<h1 class="titulo"> Zona7 </h1>
			<table>
				<tr>	
					<th class="titulosz" colspan="4">
						Motor
					</th>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Motor Cinta activo</td>
					<td class="numero" datafield = "Com2|Z7_mot1_activo"> 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Velocidad cinta</td>
					<td class="numero">  0 </td>
					<td>Hz</td>
				</tr>
				<tr>
					<th class="titulosz" colspan="4">
						Detectores
					</th>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Detector Entrada</td>
					<td class="numero" datafield = "Com2|Z7_det1"> 0  </td>
				</tr>
			</table>
		</div>
		<div class="imagen">
			<?//=  getSvg( "sheets/Images/Zona7.svg" ); ?>	
		</div>
	</div>
</div>
