<div class="main">
	
	<div class="datos">
		<div class="estados">	
			<h1 class="titulo"> Zona5 </h1>
			<table>
				<tr>	
					<th class="titulosz" colspan="4">
						Motor
					</th>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Motor Cadena activo</td>
					<td class="numero" datafield = "Com2|Z5_mot1_activo"> 0 </td>
					<td></td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Velocidad Cadena</td>
					<td class="numero">  0 </td>
					<td>Hz</td>
				</tr>
				<tr>
					<th class="titulosz" colspan="4">
						Detectores
					</th>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Detector Entrada</td>
					<td class="numero" datafield = "Com2|Z5_det1"> 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Detector Soporte</td>
					<td class="numero" datafield = "Com2|Z5_det2"> 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Detector Arriba:</td>
					<td class="numero" datafield = "Com2|Z5_det3"> 0  </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>Detector Abajo:</td>
					<td class="numero" datafield = "Com2|Z5_det4"> 0 </td>
				</tr>
				<tr>
					<th class="titulosz" colspan="4">
						Pistones
					</th>
				</tr>
				<tr>
					<td class="subtitulosz" colspan="4">
						Piston Arriba
					</td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>FC1</td>
					<td class="numero" datafield = "Com2|Z5_acc1_FC1" > 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>FC2</td>
					<td class="numero" datafield = "Com2|Z5_acc1_FC2" > 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>EV</td>
					<td class="numero" datafield = "Com2|Z5_acc1_EV" > 0 </td>
				</tr>
				<tr>
					<td class="subtitulosz" colspan="4">
						Piston Abajo
					</td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>FC1</td>
					<td class="numero" datafield = "Com2|Z5_acc2_FC1" > 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>FC2</td>
					<td class="numero" datafield = "Com2|Z5_acc2_FC2" > 0 </td>
				</tr>
				<tr>
					<td class="spacer"></td>
					<td>EV</td>
					<td class="numero" datafield = "Com2|Z5_acc2_EV" > 0 </td>
				</tr>
				
			</table>
		</div>
		<div class="imagen">
			<!-- <object type="image/svg+xml" id="svgimage" data=".\sheets\Images\Zona5.svg" ></object> -->
			<?= getSvg( "sheets/Images/Zona5.svg" ); ?>	
		</div>
	</div>
</div>

