<div class="main">
	
	<div class="datos">
		<div class="estados">	
			<h1 class="titulo"> Zona7 </h1>
			<table class= "interface">
				<tr>	
					<th colspan="2">
						Motor
					</th>
				</tr>
				<tr>
					<td>Motor Cinta activo</td>
					<td class="value">
						<span datafield="Com2|Z7_mot1_activo">0</span>
					</td>
				</tr>
				<tr>
					<td>Velocidad cinta</td>
					<td class="value">
						<span datafield="">0</span><span class="unit">Hz</span>
					</td>
				</tr>
				<tr>
					<th colspan="2">
						Detectores
					</th>
				</tr>
				<tr>
					<td>Detector Entrada</td>
					<td class="value">
						<spandatafield="Com2|Z7_det1">0</span>
					</td>
				</tr>
			</table>
		</div>
		<div class="imagen">
			<?//=  getSvg( "sheets/Images/Zona7.svg" ); ?>	
		</div>
	</div>
</div>
