<div class="main">
	
	<div class="datos">
		<div class="estados">	
			<h1 class="titulo"> Zona 1 </h1>
			<table class="interface">
				<tr>	
					<th colspan="2">
						Motor
					</th>
				</tr>
				<tr>
					<td>Motor Cadena Activo</td>
					<td class="value">
						<span datafield="Com2|Z1_mot1_activo">0</span>
					</td>
				</tr>
				<tr>
					<td>Velocidad Cadena</td>
					<td class="value">
						<span datafield="Com2|ValoresEscalados_Z1inyectorActual_output" datafixed="0">0</span><span class="unit"> Hz</span>
					</td>
				</tr>
				<tr>
					<th class="titulosz" colspan="2">
						Detectores
					</th>
				</tr>
				<tr>

					<td>Detector Entrada</td>
					<td class="value">
						<span datafield="Com2|Z1_det1">0</span>
					</td>
				</tr>
				<tr>

					<td>Detector Soporte</td>
					<td class="value">
						<span datafield="Com2|Z1_det2">0</span>
					</td>
				</tr>
				
			</table>
		</div>
	</div>
	<div class="fondo">
		<?//= getSvg( "sheets/Images/Zona1.svg" ); ?>	
	</div>
</div>
